### ISSUE TITLE
Change LaTeX renderer functionality slightly

### ISSUE THREAD

**Issue by AmoleR** [vEnhance/web.evanchen.cc#4]
Currently, `latexrender.mkd` has some really hacky JavaScript that should be updated to using [URLSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams). I'm opening an issue because any such change I make will effect other things using `latexrender` (such as Evil Chin inc.)

To fully figure out this issue, I think the following things need to be done:
 - [ ] Make sure that there is a fixed encoding (i.e. in a search query, we can not use the characters `+`, `=`, and `/`, but it can occur in a base-64 string. It's best to choose some replacement for each of these characters to avoid clashes; see [this](https://stackoverflow.com/questions/1374753/passing-base64-encoded-strings-in-url)).
 - [ ] Update `latexrender.mkd` to use the `URLSearchParams` API (see code snippet at bottom):

```js
/**
 * @todo Write tests for code
 */
$(function() {
    // https://stackoverflow.com/a/439578/4826845
    // https://stackoverflow.com/a/901144

    function decodeUrlToBase64(str) {
        // implement something
    }

    // Do a || "" to make sure that URLSearchParams doesn't throw an error for undefined
    const searchQuery = new URLSearchParams(document.location.search || "");
  
    $("#pagetitle").html(searchQuery.get("title"));
    $("div.entrywrap").html(atob(decodeUrlToBase64(searchQuery.get("content") || "")));
    MathJax.typeset();
});
```

**Comment by vEnhance** [comment]
I think `latexrender` is no longer used by anything or linked anywhere so  going to close this.
